### ISSUE TITLE
Can't get this to run

### ISSUE THREAD

**Issue by larsontim12** [telerik/blazor-stocks#3]
Can you please update the controls to work with the latest version.  I tried to upgrade them to get this to run local and it doesn't startup and connect to the service. Or give some guidance on how to get this running locally.

Thanks -Tim

**Comment by marin-bratanov** [comment]
Hi Tim,
We have not updated this app with our latest version (that is, we have not updated it to the latest WASM preview), and it brought some breaking changes on the structure of an app, you can see them here - Microsoft's blog has a guide on updating apps https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/

We will also see whether we can update this source as-is, but you should be able to update the app regardless. You could even open a Pull Request if you like.

**Comment by marin-bratanov** [comment]
I updated the app to WASM 3.2.0 Preview 1: https://github.com/telerik/blazor-stocks/commit/08b5612e1d01ea1a21eee44af3a4b88a09c6a4ba

It runs fine for me now, you should be able to pull the `master` branch and it should work for you too. Let me know if you have any issues.

**Comment by larsontim12** [comment]
Thanks for getting it updated.  I am able to get it to run but I get these errors in the browser.  I am using the licensed Telerik files from the CDN.  I appreciate the help on getting this going.  I think this sample is a good starting point to learn off of.

Thanks -Tim

Failed to load resource: the server responded with a status of 404 ()
ServiceWorkerRegister.js:17 Registration successful, scope is: https://localhost:44359/blazor-financial-portfolio/
blazor.webassembly.js:1 Blazor is running in dev mode without IL stripping. To make the bundle size significantly smaller, publish the application or see https://go.microsoft.com/fwlink/?linkid=870414
blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
blazorSize.js:24 Watch started
blazorSize.js:18 resized
blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: Microsoft.JSInterop.JSException: Could not find 'TelerikBlazor' in 'window'.
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: Error: Could not find 'TelerikBlazor' in 'window'.
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:     at https://localhost:44359/blazor-financial-portfolio/_framework/blazor.webassembly.js:1:8937
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:     at Array.forEach (<anonymous>)
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:     at p (https://localhost:44359/blazor-financial-portfolio/_framework/blazor.webassembly.js:1:8898)
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:     at https://localhost:44359/blazor-financial-portfolio/_framework/blazor.webassembly.js:1:9605

![image](https://user-images.githubusercontent.com/26381166/74557237-595ef100-4f25-11ea-8e0e-2827a1ddf7d0.png)

**Comment by marin-bratanov** [comment]
This error means that the path to the Telerik JS Interop file is wrong. See this article to copy the correct script path: https://docs.telerik.com/blazor-ui/getting-started/what-you-need#client-assets

You can also check this article on troubleshooting this: https://docs.telerik.com/blazor-ui/troubleshooting/js-errors#microsoftjsinteropjsexception-could-not-find-

Lastly, if you have altered the assets the app carries (in this case - the js file), make sure to increase the cache version of the service worker (https://github.com/telerik/blazor-stocks/blob/master/Client/BlazorFinancePortfolio.Client.csproj#L13) and fully reload the app (Ctrl + F5) - or you could use Incognito tabs until you host it on a real server, read more about this in the wiki (https://github.com/telerik/blazor-stocks/wiki/PWA-Caching) and in this blog post https://www.telerik.com/blogs/telerik-ui-for-blazor-in-a-pwa

**Comment by larsontim12** [comment]
That was the issue.  Thank you for all of your help! -Tim
