### ISSUE TITLE
Close button not visible in Chart view.

### ISSUE THREAD

**Issue by matanasov** [telerik/blazor-stocks#9]
This is an image taken on iPhone XR:

![image](https://user-images.githubusercontent.com/5861835/86261601-70963680-bbc7-11ea-9a78-2c2835e70429.png)

**Comment by marin-bratanov** [comment]
Cannot reproduce on two android devices I have, or on the available iPhones in the Chrome devtools. My best guess is some font bug with iPhone as this is merely `<span @onclick="@CloseProfile" class="k-icon icon-close"></span>`

**Comment by marin-bratanov** [comment]
Works fine on an iPhone  XS Max with iOS version 13.6

**Comment by ivanchev** [comment]
Issue is moved to: https://github.com/telerik/blazor-ui/issues/43
